### ISSUE TITLE
Left bound on cells panics example

### ISSUE THREAD

**Issue by dkettman** [briansteffens/tuig#3]
In the example provided, if I hit left when in column "A", it panics with this error:

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/briansteffens/tui.(*DetailView).Render(0xc420070200)
        /home/ubuntu/go/src/github.com/briansteffens/tui/detailview.go:150 +0x5df
github.com/briansteffens/tui.(*Container).Refresh(0xc420070280)
        /home/ubuntu/go/src/github.com/briansteffens/tui/container.go:100 +0x60
github.com/briansteffens/tui.MainLoop(0xc420070280)
        /home/ubuntu/go/src/github.com/briansteffens/tui/shared.go:189 +0x207
main.main()
        /home/ubuntu/go/src/github.com/briansteffens/tui/examples/test.go:76 +0x9c2

```

To reproduce:
1. $ go get github.com/briansteffens/tui
1. $ cd ${GOPATH}/src/github.com/briansteffens/tui/examples
1. $ go build test.go
1. $ ./test
1. Hit left arrow to cause panic

**Comment by briansteffens** [comment]
Thanks for the bug report 👍
